### PR TITLE
Add label and group array. 

### PR DESCRIPTION
**Pull request by Pshatsillo**
When you reguest state of group, it will be new array "group", where all items of the group can be found.
Label can be useful for user-friendly messages, for example Telegram or email sending

### CODE REVIEW

**Comment by jeroenhendricksen** [comment]
> When you reguest state of group, it will be new array "group", where all items of the group can be found.
> Label can be useful for user-friendly messages, for example Telegram or email sending

Thank you for your addition, which looks useful. I plan to add some (manual) tests for it, update the in-OH html documentation, update the version number and release it. If you don't mind, I'll use your branch (if I can), or create my own. Of course I'll credit you for the change. Is that ok? Is there any other way in which I can use your commit in a new branch? How does that work?

**Comment by jeroenhendricksen** [comment]
> > When you reguest state of group, it will be new array "group", where all items of the group can be found.
> > Label can be useful for user-friendly messages, for example Telegram or email sending
> 
> Thank you for your addition, which looks useful. I plan to add some (manual) tests for it, update the in-OH html documentation, update the version number and release it. If you don't mind, I'll use your branch (if I can), or create my own. Of course I'll credit you for the change. Is that ok? Is there any other way in which I can use your commit in a new branch? How does that work?

Never mind my question about pulling from your fork, I've figured it out :)

**Comment by Pshatsillo** [comment]
Hello! Of course you can use my branch as your own. Absolutely no problems.
Will wait for release! Thank you!

вт, 29 июн. 2021 г., 21:08 Jeroen Hendricksen ***@***.***>:

**Comment by jeroenhendricksen** [comment]
I've release `1.3.11` which adds support for group names. However, I choose to return them as a list. When tested from my local docker test environment, it now looks like this:

Screenshot 2021-06-29 at 21 14 37

I hope this your request for access to an item' group(s). Let me know what you think.

**Pull request closed without merging**
